### ISSUE TITLE
Setup puts the files in to ProgramFiles no matter the destination was selected

### ISSUE THREAD

**Issue by S-ed** [airbus-cert/Winshark#2]
Greeting.
The MSI installs the files into C:\Program Files\Wireshark
No matter if the different path was selected during setup.

![image](https://user-images.githubusercontent.com/3008353/102743168-f4a3cc80-4367-11eb-9a44-dfa1638fc64a.png)

**Comment by citronneur** [comment]
Fixed in Release v1.1.0.
Thanks!
