### ISSUE TITLE
ETW already present in 3.6.0

### ISSUE THREAD

**Issue by ruudsieb** [airbus-cert/Winshark#4]
Protocol "etw" is already present resulting in errors during Wireshark startup.
See:
[https://www.wireshark.org/docs/dfref//e/etw.html](https://www.wireshark.org/docs/dfref//e/etw.html)

**Comment by citronneur** [comment]
Thanks a lot, We will fix it in the next release!

**Comment by citronneur** [comment]
Fixed in Release 1.1.0, I had to rename the protocol from ETW to winshark because the ETW in wireshark is docussed on ETL...
