### ISSUE TITLE
No physical interfaces after Winshark installation

### ISSUE THREAD

**Issue by killthepatate** [airbus-cert/Winshark#5]
Hello,

Great work, i can now put together network trafic and processID. I use netsh and logam.

But i have one problem, i can't see my physical network adapter when i launch wireshark and i'm not able to lauch a capture on this network adapters.

Do you have a solution in order to see it ? 

Thank you

**Comment by citronneur** [comment]
Hi Killthepatate,

Sorry but it's not possible. In Winshark we are replace the library which is in charge of network capture, by one that can do ETW capture.

You have to install a normal Wireshark in another location.

Have a nice day,

Sylvain Peyrefitte
